server:
  port: 8089
  
spring:
  application:
    name: API_GATEWAY
    
    
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200" # or "*" to allow all origins
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*" # or specify headers
#            allowCredentials: true
#      routes:
#      - id: gestionenseignantcontrat
#        uri:
#          lb://gestionenseignantcontrat
#        predicates:
#        - Path=/api/**

  cloud:
    gateway:
      routes:
        - id: activiteprogramme
          uri: lb://activiteprogramme
          predicates:
            - Path=/api/candidats/**




